### ISSUE TITLE
[Setup Support] Including a tutorial for standing up own instance of Perseus using Docker

### ISSUE THREAD

**Issue by ssamus** [OHDSI/Perseus#12]

**Comment by ssamus** [comment]
Hi @Zwky26 We have instructions on GitHub https://github.com/OHDSI/Perseus#starting-with-docker-compose Could you please explain what you expect the results to be?

**Comment by Zwky26** [comment]
Further user feedback specified that the issue is related to errors of current Docker compose code, not on lack of documentation. This issue is duplicate of #7, so this issue can be closed.

**Comment by ssamus** [comment]
Duplicate
