### ISSUE TITLE
[Low Prio] REQUEST: Port wiki from old repo to OHDSI repo

### ISSUE THREAD

**Issue by Zwky26** [OHDSI/Perseus#16]
For consistency purposes, moving the wiki from [the old repo](https://github.com/SoftwareCountry/Perseus/wiki) to this one should be eventually done, as we are recommending future users only refer to this repo for information.

Additionally, updating the wiki section of "Convert native to CDM" with a more explicit example of connection string (see below) has been a common user request.

![image](https://user-images.githubusercontent.com/59004211/198485863-29fc145a-e6b8-476a-ba05-e2093709bd6d.png)

**Comment by bradanton** [comment]
@Zwky26 What kind of examples do you mean? 
https://github.com/SoftwareCountry/Perseus/wiki/Convert-native-to-CDM has gif with sample, screenshot below.

![image](https://user-images.githubusercontent.com/13117785/199670875-c005244a-918e-4cda-a159-ef270abf77c2.png)

**Comment by Zwky26** [comment]
Having examples of specific connection string format, i.e. for Azure connection it specifically will say
"servername.database.windows.net" instead of just "servername". 

Same would go for Postgres, MySQL, and SQL Server connection. Having a concrete example, so
"Server Location" would be exact format of IP address required so "000.00.00...." (depending on what is intended, unsure of exact spec) and not just "server_ip_address" to improve clarity of requirements.

**Comment by bradanton** [comment]
@Zwky26 https://github.com/SoftwareCountry/Perseus/wiki/Convert-native-to-CDM#connection-string-examples

**Comment by bradanton** [comment]
Cloned to OHDSI
