### ISSUE TITLE
Feature (Low Prio): Sort USAGI results by Match Score

### ISSUE THREAD

**Issue by Zwky26** [OHDSI/Perseus#2]
Feedback received during demo: as implemented in the Java app version, being able to click on the header to enable "Sort by Match Score Ascending" or "Descending" would be a small but appreciated quality-of-life change

**Comment by chMatvey** [comment]
Hi @Zwky26,
Implemented, can you please check?

**Comment by Zwky26** [comment]
Tested and verified working!
