### ISSUE TITLE
[Feature request] Provide option for non-standard certificates

### ISSUE THREAD

**Issue by gmestdac** [OHDSI/Perseus#25]
Note: my knowledge of certificates is very limited, so expect vagueness in my description

I am trying to install and run Perseus on my work computer. 
The company I work for issues its own certificates so that network traffic can be inspected.
This causes for example RUN npm install to fail due to certificate checks failing,  which I got past by setting  npm config set strict-ssl false
 
 I believe this new issue I ran into (log below) is caused by a similar problem. 
 Given that Perseus is to be used within hospital networks I assume I am not the only person to face similar problems.
 Could you think of a secure way of dealing with this? For example by (optionally) manually providing the certificate to be trusted within the setup/containers?
 
 
  => ERROR [build  7/10] RUN dotnet restore "org.ohdsi.cdm.presentation.builderwebapi/org.ohdsi.cdm.presentation.builderwebapi.csproj  12.7s
------
 > [build  7/10] RUN dotnet restore "org.ohdsi.cdm.presentation.builderwebapi/org.ohdsi.cdm.presentation.builderwebapi.csproj":
#22 3.366   Determining projects to restore...
#22 7.071   Restored /src/org.ohdsi.cdm.framework.common/org.ohdsi.cdm.framework.common.csproj (in 298 ms).
#22 7.072   Restored /src/org.ohdsi.cdm.framework.etl/org.ohdsi.cdm.framework.etl.common/org.ohdsi.cdm.framework.etl.common.csproj (in 298 ms).
#22 7.548 /usr/share/dotnet/sdk/3.1.426/NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/src/org.ohdsi.cdm.presentation.builderwebapi/org.ohdsi.cdm.presentation.builderwebapi.csproj]ntation.  12.7s
#22 7.548 /usr/share/dotnet/sdk/3.1.426/NuGet.targets(128,5): error :   The SSL connection could not be established, see inner exception. [/src/org.ohdsi.cdm.presentation.builderwebapi/org.ohdsi.cdm.presentation.builderwebapi.csproj]
#22 7.548 /usr/share/dotnet/sdk/3.1.426/NuGet.targets(128,5): error :   The remote certificate is invalid according to the validation procedure. [/src/org.ohdsi.cdm.presentation.builderwebapi/org.ohdsi.cdm.presentation.builderwebapi.csproj]

**Comment by kostiushenko** [comment]
Try to add your CA cert file to container. Modify Dockerfile adding these lines:

# Certicate
ENV CERT_HOME=/usr/local/share/ca-certificates
ENV CERT_FILE_PATH=${CERT_HOME}/my.crt
RUN mkdir -p ${CERT_HOME}
ADD my.crt ${CERT_FILE_PATH}
RUN apt-get update && apt-get install -y ca-certificates
RUN update-ca-certificates

# npm settings
RUN npm config set cafile ${CERT_FILE_PATH}
