### ISSUE TITLE
BUG (Low Prio/Edge Case): Create View fails to work when table name capitalized

### ISSUE THREAD

**Issue by Zwky26** [OHDSI/Perseus#3]
An edge case occurs when creating a View that does not resolve, but also does not throw any error. Table names are censored for 
proprietary reasons. 

https://user-images.githubusercontent.com/59004211/184387328-0221b11e-3d19-498d-ada0-a7cd44cc1aea.mov

``` 
SELECT DISTINCT pos.*
    FROM table0
	INNER join table1
	    ON table1.pat_id = table0.epic_pat_id
	INNER JOIN TABLE2 AS pos
	    ON table1.cur_prim_loc_id = pos.pos_id
```	
 
Edge case occurs when TABLE2 is capitalized. Changing it to lowercase allows it to run without issue. Error only occurs when joining using a capitalized table. When simply doing
```
SELECT DISTINCT *
    FROM TABLE2
```
the capitalization does not have an effect. 

Also, edge case only occurs when joining multiple tables( does not occur when joining exactly 2 tables total)

**Comment by chMatvey** [comment]
Hi @Zwky26 ,
Perseus use postgre database and postgre SQL syntax. In postgre syntax there are two types of identifiers: unquoted and quoted. [documentation](https://www.postgresql.org/docs/current/sql-syntax-lexical.html)
If original table name in lowercase, Perseuse uses unquoted identifier, in uppercase or various case - quoted.
I tried to reproduce your example, screen below:
![Screenshot1 2022-08-16 в 13 44 53](https://user-images.githubusercontent.com/40443101/184861197-71791df1-f4df-4aa3-bcbc-29e771408b4d.png)
Table0 with unquoted identifier can be written with any case in view SQL query and it would be work:
![Screenshot2 2022-08-16 в 13 48 49](https://user-images.githubusercontent.com/40443101/184861864-6fd8712f-fdd2-49f5-b125-77546df0898e.png)
or
![Screenshot3 2022-08-16 в 13 54 21](https://user-images.githubusercontent.com/40443101/184862842-eef75eaa-f9bb-4239-9ad1-0118172d93a4.png)
But with TABLE2 you should use quoted identifier rules. Your example would be like this:
![Screenshot4 2022-08-16 в 13 51 13](https://user-images.githubusercontent.com/40443101/184862286-223be353-8882-46cf-9e8d-c600c98847c2.png)

`SELECT DISTINCT * FROM "TABLE2"`

**Comment by Zwky26** [comment]
Confirmed that it works just as you said. Thank you for letting me know- issue can be closed, and also combined with https://github.com/SoftwareCountry/Perseus/issues/627 for future implementation of sanitization protocol of naming conventions
