### ISSUE TITLE
Automatically build Perseus Docker container images and push to Docker Hub when code changes in GitHub

### ISSUE THREAD

**Issue by leeevans** [OHDSI/Perseus#30]
Automatically build Perseus Docker container images and push them to Docker Hub when code changes are pushed to the OHDSI Perseus github repo. Tag the Docker image with a version number.

Benefits of this change: 

- It will ensure that we always have the latest Perseus Docker images in Docker Hub.
- It is much faster to deploy Perseus using pre-built Docker Hub images instead of building them locally

One way to accomplish this is to develop GitHub Actions

**Comment by ssamus** [comment]
Done
