### ISSUE TITLE
update Perseus docker-compose.yaml file to download pre-built Perseus Docker images in Docker Hub

### ISSUE THREAD

**Issue by leeevans** [OHDSI/Perseus#31]
Currently the Perseus docker-compose.yml file is configured to build the  Perseus Docker images locally.
This results in a very time consuming process for deployment of Perseus for end users.

Action:

Update the Perseus docker compose yaml file configuration to pull the latest pre-built Perseus Docker images from Docker Hub. Also update the README.md documentation to reflect this change.

See also github action #30 which ensures that the latest Perseus Docker images are maintained in Docker Hub

**Comment by alabarga** [comment]
any timeline for this? I just tried to build it locally but got errors related to node

**Comment by kostiushenko** [comment]
https://hub.docker.com/repositories/perseushub
We have created Docker Hub repositories.
All builds push images to Docker Hub from now on.
Docker compose file also updated to work with Docker Hub images.

Use:
```
docker compose pull
docker compose up -d
```

**Comment by ssamus** [comment]
Done
