### ISSUE TITLE
bug when loading a scan report

### ISSUE THREAD

**Issue by natb1** [OHDSI/Perseus#35]
After doing a clean build of Perseus I get the following error from _create_source_schema_by_scan_report:

(full stack below)
__init__() got multiple values for argument 'schema'

Looking at this
https://stackoverflow.com/questions/75282511/df-to-table-throw-error-typeerror-init-got-multiple-values-for-argument
suggests that the issue could have to do with pandas version mismatches. I'll also attach a pip freeze.

1. Has anybody else encountered this?
2. The version of pandas is quite old, many of the libraries are several years old (namely Angular) and this creates a number of landmines when debugging/dev'ing. Are there any prospects for getting the libs up to date. I suspect this would be a prerequisite for most new work.

[2023-04-14 02:35:28,397] ERROR: http://localhost/backend/api/create_source_schema_by_scan_report request returned error: __init__() got multiple values for argument 'schema'
backend                   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
backend                   |     rv = self.dispatch_request()
backend                   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
backend                   |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
backend                   |   File "/app/utils/username_header.py", line 12, in decorator
backend                   |     return f(current_user, *args, **kwargs)
backend                   |   File "/app/perseus_api.py", line 82, in create_source_schema_by_scan_report
backend                   |     raise error
backend                   |   File "/app/perseus_api.py", line 78, in create_source_schema_by_scan_report
backend                   |     .create_source_schema_by_scan_report(current_user, etl_mapping.id, etl_mapping.scan_report_name)
backend                   |   File "/app/services/source_schema_service.py", line 32, in create_source_schema_by_scan_report
backend                   |     return _create_source_schema_by_scan_report(username, etl_mapping_id, scan_report_path)
backend                   |   File "/app/services/source_schema_service.py", line 92, in _create_source_schema_by_scan_report
backend                   |     raise e
backend                   |   File "/app/services/source_schema_service.py", line 55, in _create_source_schema_by_scan_report
backend                   |     from overview group by `table`;""")
backend                   |   File "/usr/local/lib/python3.7/site-packages/pandasql/sqldf.py", line 156, in sqldf
backend                   |     return PandaSQL(db_uri)(query, env)
backend                   |   File "/usr/local/lib/python3.7/site-packages/pandasql/sqldf.py", line 58, in __call__
backend                   |     write_table(env[table_name], table_name, conn)
backend                   |   File "/usr/local/lib/python3.7/site-packages/pandasql/sqldf.py", line 121, in write_table
backend                   |     index=not any(name is None for name in df.index.names))  # load index into db if all levels are named
backend                   |   File "/usr/local/lib/python3.7/site-packages/pandas/io/sql.py", line 440, in to_sql
backend                   |     pandas_sql = pandasSQL_builder(con, schema=schema)
backend                   |   File "/usr/local/lib/python3.7/site-packages/pandas/io/sql.py", line 508, in pandasSQL_builder
backend                   |     return SQLDatabase(con, schema=schema, meta=meta)
backend                   |   File "/usr/local/lib/python3.7/site-packages/pandas/io/sql.py", line 940, in __init__
backend                   |     meta = MetaData(self.connectable, schema=schema)

APScheduler==3.9.1
azure-common==1.1.28
azure-core==1.26.4
azure-identity==1.10.0
azure-keyvault-secrets==4.4.0
backports.zoneinfo==0.2.1
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
cryptography==40.0.1
Flask==2.0.3
Flask-Cors==3.0.10
greenlet==2.0.2
idna==3.4
importlib-metadata==6.3.0
isodate==0.6.1
itsdangerous==2.1.2
Jinja2==3.1.2
MarkupSafe==2.1.2
msal==1.21.0
msal-extensions==1.0.0
msrest==0.7.1
numpy==1.21.6
oauthlib==3.2.2
pandas==0.23.4
pandasql==0.7.3
peewee==3.16.0
portalocker==2.7.0
psycopg2-binary==2.9.6
py-postgresql==1.2.2
pycparser==2.21
PyJWT==2.6.0
python-dateutil==2.8.2
pytz==2023.3
pytz-deprecation-shim==0.1.0.post0
requests==2.28.2
requests-oauthlib==1.3.1
six==1.16.0
SQLAlchemy==2.0.9
typing_extensions==4.5.0
tzdata==2023.3
tzlocal==4.3
urllib3==1.26.15
waitress==2.1.2
Werkzeug==2.2.3
xlrd==1.2.0
zipp==3.15.0

**Comment by natb1** [comment]
this bug is reproducible in the images new images from docker #31

**Comment by ssamus** [comment]
@bradanton please investigate the issue asap

**Comment by alondhe** [comment]
Seeing the same error as well

`(Failed to load report: __init__() got multiple values for argument 'schema')`

**Comment by bradanton** [comment]
the issue was fixed, should work now.
