### ISSUE TITLE
MacOS Port 5000 conflict

### ISSUE THREAD

**Issue by sudoshi** [OHDSI/Perseus#36]
As you know I was having a strange problem with a conflict on port 5000.

I found the issue! And I wanted to alert you so that you can inform the broader community of potential users who might try to use Docker Desktop for Mac OS, especially since Monterrey and currrently with Ventura releases of the OS.

Apple uses port 5000 for incoming requests to Airplay music from devices to the MacOS machine. Turning this off is simple:
![796267e6b060412e25a2785d60c4b6a2bc36f865_2_495x500](https://user-images.githubusercontent.com/100962480/233151811-42d2ae0f-e701-4fdc-87fc-14d08d18cb2e.png)

**Comment by ssamus** [comment]
hi @sudoshi,

Pls have a look at the following items https://github.com/OHDSI/Perseus/issues/19 it is the same issue.
