### ISSUE TITLE
[BUG] SQL transformations result in "Relation does not exist" error when mapping from CSV file

### ISSUE THREAD

**Issue by kzollove** [OHDSI/Perseus#38]
I am using a csv file perseusDemoTable, and getting this error when I attempt to use any transformations:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/18039765/235519425-8bd5aa7c-4e5f-44dd-b2ce-4b076f38c4da.png)

SOLVED: The problem goes away when I rename the csv file perseusdemotable (no caps) and re-scan data

**Comment by bradanton** [comment]
Can you share the csv file that cause the error?

**Comment by kzollove** [comment]
[perseusDemoTable.csv](https://github.com/OHDSI/Perseus/files/11373628/perseusDemoTable.csv)

**Comment by bradanton** [comment]
fix was added to perseus-api
