### ISSUE TITLE
[BUG] Can not cast as datetime (only timestamp)

### ISSUE THREAD

**Issue by kzollove** [OHDSI/Perseus#39]
Can not cast a csv column read in as Date type as datetime. I am able to cast as timestamp. While this is probably sufficient, its a bit confusing as Type is listed as Datetime in the target table for birth_datetime

![image](https://user-images.githubusercontent.com/18039765/235520598-2db23381-34b7-4aa3-9a69-387fe7ebfdfc.png)

**Comment by bradanton** [comment]
PostgreSQL doesn't have datetime data type. You can use following: CAST(deathdate as timestamp without time zone)
We will try to fix it soon.

**Comment by bradanton** [comment]
schema was updated 
![image](https://github.com/OHDSI/Perseus/assets/13117785/eef8e497-ef16-45bf-8964-7244b48b351f)
