### ISSUE TITLE
(Med-High Prio) Bug: Request to "Convert to CDM" breaks, path missing

### ISSUE THREAD

**Issue by Zwky26** [OHDSI/Perseus#4]
After connecting to an Azure SQL database, clicking the "Convert to CDM" and sending the actual request runs into error. It seems like part of requests go through, and server receives them as activity spikes, but no changes are actually finished and pushed to server. Full error message is below
![image](https://user-images.githubusercontent.com/59004211/189170065-223b1a83-aeb5-4ef0-b5a4-aa7cbc6e120f.png)

![image](https://user-images.githubusercontent.com/59004211/189169747-8c458387-26d0-4781-a137-9c3ee144f601.png)

Creating CDM database...
Warning: CDM database exists
Warning: CDM schema exists
Warning: CDM tables exists
CDM tables truncated
Loading locations...
Locations was loaded
Loading care sites...
Care sites was loaded
Loading providers...
Providers was loaded
Saving lookups...
Lookups was saved
CMSPlaceOfService - Loading ...
DONE - 73 ms | KeysCount=260
CMSPlaceOfService - Uploading to File Manager...
CMSPlaceOfService - Uploading DONE
Could not find a part of the path '/app/ETL/Common/Scripts/PostgreSQL/DropChunkTable.sql'.

**Comment by bradanton** [comment]
@Zwky26 I have added fix, please try now.

**Comment by Zwky26** [comment]
Tried and got a new message. This seems to be related to my postgres syntax and not any tech issue, and I am working on it. I will update if any other issues related to connections arise
![image](https://user-images.githubusercontent.com/59004211/189375173-25e3b283-06cb-4543-88ee-5412a0b08812.png)
