### ISSUE TITLE
Scan report fails to load

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Perseus#51]
I tried loading CSV files, it works, builds the scan report. But then trying to use the scan report gives this error:

`Failed to load report: type "empty" does not exist LINE 1: ...RCHAR(15),"Page" INT,"Item" INT,"PatientDataType" EMPTY,"Pag... ^`

**Comment by alondhe** [comment]
I was using a licensed data set, so I can't. I'll try again with public data.

**Comment by katy-sadowski** [comment]
I just ran into the same issue. For me, this occurred when a column in the source dataset had all null values. The scan report lists the data type for this column as `EMPTY`.

Source table and scan report are attached (this is a public dataset from Phuse) - the column in question is `RFICDTC`.

Source: [dm.csv](https://github.com/OHDSI/Perseus/files/12255096/dm.csv)
Scan report: [csv.xlsx](https://github.com/OHDSI/Perseus/files/12255106/csv.xlsx)

**Comment by bradanton** [comment]
fix was added to perseus-api
