### ISSUE TITLE
CDM-Builder app settings question

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Perseus#53]
Hi @bradanton - for the CDM Builder docker image, is it possible to pass environment variables in to modify settings in the appsettings json file?

https://github.com/SoftwareCountry/ETL-CDMBuilder/blob/master/source/org.ohdsi.cdm.presentation.builderwebapi/appsettings.Docker.json

Settings like FilesManagerUrl, SourceDbHost, VocabularyDbHost. Or do we need to add a new appsettings json file for Broadsea?

**Comment by bradanton** [comment]
Hi @alondhe, yes it possible, you can modify settings. I will update the CDM Builder if needed.

**Comment by ssamus** [comment]
Done
