### ISSUE TITLE
[FEATURE REQUEST] Add a To-Do List to Repo

### ISSUE THREAD

**Issue by Zwky26** [OHDSI/Perseus#9]
Userbase has requests for future functionalities/changes to support. As many of these are long term projects, we should not categorized as "issues" but instead feature requests. To prevent Issues Tab from overflowing with feature requests, can we add a "To-Do" list within the Readme or a KanBan Board similar to [the one on the Software County repo](https://github.com/SoftwareCountry/Perseus/projects/1)?

Most highly requested features:

- [ATHENA API] Allow calling functions such as: see version type, force pull most recent vocab version
- [Databricks Connection] Support connection endpoint to databricks environment. Long term project 
- [Setup Support] Including a tutorial for standing up own instance of Perseus using Docker

**Comment by ssamus** [comment]
@leeevans Please provide permission to create the Project(Board) https://github.com/OHDSI/Perseus/projects?query=is%3Aopen for managing tasks. Current moment I cannot to do the new project.

**Comment by leeevans** [comment]
new OHDSI Perseus project board created here:
https://github.com/orgs/OHDSI/projects/12

**Comment by natb1** [comment]
Hi @leeevans I would like to understand the Perseus activities and roadmap better. The above link gives me a 404. This may be because I do not have the right permissions. Could you please let me know the process for getting access to the "project board".

**Comment by leeevans** [comment]
Hi @natb1 I've made it public now.

**Comment by ssamus** [comment]
Three separate items were created. Work will continue under these items
